Repository estuary/connectors, pull requests merged in 2024-09, with the labels that each got.

#1894 materialize-bigquery: log failed load queries
  materialize-bigquery/transactor.go
Labels: change:unplanned

#1892 materialize-*: x-schema-name and x-delta-updates annotations
  go/schema-gen/generate.go
  materialize-bigquery/.snapshots/TestSpecification
  materialize-bigquery/bigquery.go
  materialize-databricks/.snapshots/TestSpecification
  materialize-databricks/driver.go
  materialize-dynamodb/.snapshots/TestSpec
  materialize-dynamodb/driver.go
  materialize-elasticsearch/.snapshots/TestDriverSpec
  materialize-elasticsearch/driver.go
  materialize-mongodb/.snapshots/TestSpecification
  materialize-mongodb/config.go
  materialize-motherduck/.snapshots/TestSpecification
  materialize-motherduck/driver.go
  materialize-mysql/.snapshots/TestSpecification
  materialize-mysql/driver.go
  materialize-postgres/.snapshots/TestSpecification
  materialize-postgres/driver.go
  materialize-redshift/.snapshots/TestSpecification
  materialize-redshift/driver.go
  materialize-snowflake/.snapshots/TestSpecification
  materialize-snowflake/snowflake.go
  materialize-sqlserver/.snapshots/TestSpecification
  materialize-sqlserver/driver.go
  materialize-starburst/.snapshots/TestSpecification
  materialize-starburst/starburst.go
Labels: change:planned

#1895 source-zendesk-support: fix `ticket_metrics` and `ticket_metric_events`
  source-zendesk-support/source_zendesk_support/streams.py
  source-zendesk-support/test.flow.yaml
  source-zendesk-support/tests/snapshots/snapshots__discover__capture.stdout.json
  source-zendesk-support/tests/unit_test.py
Labels: change:planned

#1896 tests: use flowctl raw discover instead of flowctl-go in capture tests
  tests/run.sh
Labels: change:unplanned

#1898 materialize-postgres: don't allow supabase connection pooler addresses
  materialize-postgres/driver.go
Labels: change:unplanned

#1901 source-hubspot-native: a few enhancements
  source-hubspot-native/source_hubspot_native/api.py
Labels: change:unplanned

#1902 source-hubspot-native: debug logging for fetching search objects
  source-hubspot-native/source_hubspot_native/api.py
Labels: change:unplanned

#1903 sqlcapture: Implement an ugly but functional replication cursor replacement mechanism
  sqlcapture/main.go
Labels: change:unplanned

#1904 sqlcapture: Two more production cursor replacements
  sqlcapture/main.go
Labels: change:unplanned

#1906 source-hubspot-native: handle search API results larger than 10,000 records
  source-hubspot-native/source_hubspot_native/api.py
Labels: change:unplanned

#1910 source-mysql: Send a 'Keepalive Event' for inactive table changes
  source-mysql/replication.go
  sqlcapture/capture.go
  sqlcapture/interface.go
Labels: change:planned

#1921 materialize-s3-iceberg: use table paths of loaded tables
  materialize-s3-iceberg/catalog.go
  materialize-s3-iceberg/driver.go
  materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
  materialize-s3-iceberg/icebergctl.go
  materialize-s3-iceberg/transactor.go
Labels: change:unplanned

#1924 source-mysql-batch: Improve connection error reporting
  source-mysql-batch/main.go
Labels: change:unplanned

#1911 materialize-postgres: separate table create error for user-supplied additional SQL
  materialize-postgres/client.go
Labels: change:unplanned

#1936 materialize-s3-iceberg: don't use context manager for transaction
  materialize-s3-iceberg/iceberg-ctl/iceberg_ctl/__main__.py
Labels: change:unplanned

#1933 source-mongodb: merge deletion events
  source-mongodb/.snapshots/TestDiscover
  source-mongodb/.snapshots/TestDiscoverAllDatabases
  source-mongodb/.snapshots/TestDiscoverMultipleDatabases
  source-mongodb/discovery.go
Labels: change:unplanned

#1937 materialize-dynamodb: log failed batch writes in stores
  materialize-dynamodb/transactor.go
Labels: change:unplanned

#1934 source-http-ingest: update dependencies
  source-http-ingest/Cargo.lock
  source-http-ingest/Cargo.toml
  source-http-ingest/src/lib.rs
Labels: dependencies

#1913 materialize-redshift: flush bindings when stores are complete
  materialize-redshift/driver.go
Labels: change:planned

#1944 source-mysql: Replace date `0000-00-00` with `0001-01-01`
  source-mysql/datatype_test.go
  source-mysql/discovery.go
Labels: change:unplanned

#1945 sqlcapture: Require backfill increment when mode changes
  sqlcapture/main.go
Labels: change:planned

#1938 source-brevo: import to Estuary CDK
  .github/workflows/python.yaml
  source-brevo/VERSION
  source-brevo/acmeCo/flow.yaml
  source-brevo/poetry.lock
  source-brevo/pyproject.toml
  source-brevo/source_brevo/__init__.py
  source-brevo/source_brevo/__main__.py
  source-brevo/source_brevo/manifest.yaml
  source-brevo/source_brevo/source.py
  source-brevo/test.flow.yaml
  source-brevo/tests/__init__.py
  source-brevo/tests/snapshots/snapshots__discover__capture.stdout.json
  source-brevo/tests/snapshots/snapshots__spec__capture.stdout.json
  source-brevo/tests/test_snapshots.py
Labels: change:planned

#1962 source-stripe-native: fix incremental logic
  source-stripe-native/source_stripe_native/api.py
Labels: change:unplanned

#1961 materialize-motherduck: add more reserved words
  go.mod
  go.sum
  materialize-motherduck/.snapshots/TestSQLGeneration
  materialize-motherduck/reserved_words.go
  tests/materialize/materialize-motherduck/config.yaml
  tests/materialize/materialize-motherduck/snapshot.json
Labels: change:unplanned

#1964 stream-encode: parquet encoder handles integers that are floats
  materialize-boilerplate/stream-encode/parquet.go
Labels: change:unplanned

#1966 source-postgres: Discover OIDs as integers and add tests
  source-postgres/.snapshots/TestScanKeyTypes-OID
  source-postgres/datatype_test.go
  source-postgres/discovery.go
Labels: change:unplanned

#1972 materialize-snowflake: percent encode username + password input
  materialize-snowflake/.snapshots/TestConfigURI-User_&_Password_Authentication
  materialize-snowflake/.snapshots/TestConfigURI-v1_User_&_Password_Authentication
  materialize-snowflake/.snapshots/TestConfigURI-v2_User_&_Password_Authentication
  materialize-snowflake/config.go
  materialize-snowflake/config_test.go
Labels: change:unplanned

#1975 source-postgres: Exclude `pglogical` schema from discovery
  source-postgres/discovery.go
Labels: change:unplanned

#1978 source-stripe-native: make created optional for Accounts
  source-stripe-native/source_stripe_native/models.py
  source-stripe-native/tests/snapshots/snapshots__discover__stdout.json
Labels: change:unplanned

#1982 source-stripe-native: handle responses for children of deleted resources
  source-stripe-native/source_stripe_native/api.py
  source-stripe-native/source_stripe_native/models.py
Labels: change:unplanned

#1986 source-stripe-native: handle UsageRecords 400 response
  source-stripe-native/source_stripe_native/api.py
Labels: change:unplanned

#1991 source-zendesk-support: update capture snapshot
  source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
Labels: change:unplanned

#1967 Wihl/source brevo
  source-brevo/acmeCo/flow.yaml
  source-brevo/poetry.lock
  source-brevo/pyproject.toml
  source-brevo/source_brevo/manifest.yaml
  source-brevo/test.flow.yaml
  source-brevo/tests/snapshots/snapshots__discover__capture.stdout.json
Labels: change:planned

#1996 materializations: use correct resource path when building InfoSchema in Open
  materialize-sql/driver.go
Labels: change:unplanned
