Repository estuary/connectors, pull requests merged in 2024-12, with the labels that each got.

#2175 network-tunnel: Don't fail on Stop() of nil tunnel
  go/network-tunnel/network_tunnel.go
Labels: change:unplanned

#2182 source-twilio: improve MessageMedia incremental sync speed
  source-twilio/source_twilio/streams.py
Labels: change:unplanned

#2193 source-braintree-native: concatenate search limit error message
  source-braintree-native/source_braintree_native/api.py
Labels: change:unplanned

#2195 source-braintree-native: run synchronous API calls in separate threads
  source-braintree-native/source_braintree_native/api.py
Labels: change:unplanned

#2218 source-genesys: fix `conversations` default param bug
  source-genesys/source_genesys/api.py
Labels: change:unplanned

#2219 source-*-batch: Add missing network-tunnel binary
  source-bigquery-batch/Dockerfile
  source-mysql-batch/Dockerfile
  source-postgres-batch/Dockerfile
  source-redshift-batch/Dockerfile
Labels: change:unplanned

#2222 source-hubspot-native: conditionally discover `email_events` binding
  source-hubspot-native/source_hubspot_native/resources.py
  source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json
Labels: change:planned

#2227 source-oracle-flashback: debug logs in backfill
  source-oracle-flashback/source_oracle_flashback/api.py
  source-oracle-flashback/source_oracle_flashback/resources.py
Labels: change:emergency

#2228 source-oracle-flashback: fix test SSH key (key has been rotated)
  source-oracle-flashback/config.yaml
Labels: change:emergency

#2231 kafka: SASL mechanism must have a dash between before numbers
  materialize-kafka/src/configuration.rs
  source-kafka/src/configuration.rs
Labels: change:unplanned
