Repository estuary/connectors, pull requests merged in 2024-10, with the labels that each got.

#2007 source-zendesk-support: fix Groups and Organizations streams
  source-zendesk-support/source_zendesk_support/streams.py
  source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
  source-zendesk-support/tests/test_futures.py
  source-zendesk-support/tests/unit_test.py
Labels: change:unplanned

#2014 source-zendesk-support: checkpoint `TicketMetricEvents` state after every 1000 documents
  source-zendesk-support/source_zendesk_support/streams.py
Labels: change:unplanned

#2020 source-pendo: validate API key
  source-pendo/source_pendo/__init__.py
  source-pendo/source_pendo/resources.py
Labels: change:unplanned

#2021 materialize-pinecone: update to Pinecone Go SDK
  go.mod
  go.sum
  materialize-pinecone/.snapshots/TestSpecification
  materialize-pinecone/client/client.go
  materialize-pinecone/driver.go
  materialize-pinecone/transactor.go
  tests/materialize/materialize-pinecone/cleanup.sh
  tests/materialize/materialize-pinecone/config-extra.json
  tests/materialize/materialize-pinecone/config.yaml
  tests/materialize/materialize-pinecone/fetch-data.go
  tests/materialize/materialize-pinecone/setup.sh
  tests/materialize/materialize-pinecone/snapshot.json
Labels: change:planned

#2029 materialize-redshift: fix logging of Store bindings with no data
  materialize-redshift/driver.go
Labels: change:unplanned

#2031 source-mysql: More connection error logging
  source-mysql-batch/main.go
  source-mysql/main.go
Labels: change:unplanned

#2034 source-http-ingest: use proper schema uri
  source-http-ingest/src/server.rs
  source-http-ingest/tests/test.rs
Labels: bug, change:unplanned

#2035 source-postgres: Discover 'citext' columns as strings
  source-postgres/discovery.go
Labels: change:unplanned

#2036 materialize-sql: only evaluate migrations for selected fields
  materialize-sql/apply.go
Labels: change:unplanned

#2042 source-postgres: Add 'Discover Only Published Tables' setting
  source-postgres/.snapshots/TestGeneric-SpecResponse
  source-postgres/database.go
  source-postgres/discovery.go
  source-postgres/main.go
  source-postgres/prerequisites.go
Labels: change:unplanned

#2043 materialize: don't use locks in the extended logger
  materialize-boilerplate/logging.go
Labels: change:unplanned

#2044 source-zendesk-support: omit tags from capture snapshot
  source-zendesk-support/tests/snapshots/snapshots__capture__capture.stdout.json
  source-zendesk-support/tests/test_snapshots.py
Labels: change:unplanned

#2045 materialize-sql: migrate to JSON type when possible
  materialize-bigquery/.snapshots/TestValidateAndApplyMigrations
  materialize-bigquery/sqlgen.go
  materialize-databricks/.snapshots/TestValidateAndApplyMigrations
  materialize-motherduck/.snapshots/TestValidateAndApplyMigrations
  materialize-motherduck/sqlgen.go
  materialize-mysql/.snapshots/TestValidateAndApplyMigrations
  materialize-mysql/sqlgen.go
  materialize-postgres/.snapshots/TestValidateAndApplyMigrations
  materialize-postgres/sqlgen.go
  materialize-redshift/.snapshots/TestValidateAndApplyMigrations
  materialize-redshift/sqlgen.go
  materialize-snowflake/.snapshots/TestValidateAndApplyMigrations
  materialize-snowflake/sqlgen.go
  materialize-sql/.snapshots/TestValidateMigrations
  materialize-sql/migration_mapping.go
  materialize-sql/test_support.go
  materialize-sql/testdata/validate/base.flow.yaml
  materialize-sql/testdata/validate/generated_specs/base.flow.proto
  materialize-sql/testdata/validate/generated_specs/migratable-changes.flow.proto
  materialize-sql/testdata/validate/migratable-changes.flow.yaml
  materialize-sqlserver/.snapshots/TestValidateAndApplyMigrations
  materialize-sqlserver/sqlgen.go
Labels: change:planned

#2054 source-postgres: Don't fetch column descriptions in system schemas
  source-postgres/discovery.go
Labels: change:unplanned

#2055 materialize: add missing log message for when evaluating loads starts
  materialize-boilerplate/logging.go
Labels: change:unplanned

#2058 source-mysql: Fix some benign error/warnings that get logged
  source-mysql/discovery.go
  source-mysql/replication.go
Labels: change:unplanned

#2064 source-hubspot-native: custom object path components
  source-hubspot-native/source_hubspot_native/resources.py
Labels: change:unplanned

#2065 source-hubspot-native: add "FORWARD" to email event types
  source-hubspot-native/source_hubspot_native/models.py
  source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json
Labels: change:unplanned

#2066 source-hubspot-native: add more email event types
  source-hubspot-native/source_hubspot_native/models.py
  source-hubspot-native/tests/snapshots/snapshots__discover__stdout.json
Labels: change:unplanned

#2069 source-hubspot-native: add auto backfills for delayed streams
  source-hubspot-native/source_hubspot_native/api.py
Labels: change:unplanned

#2070 source-zendesk-support: checkpoint during `AuditLogs` stream
  source-zendesk-support/source_zendesk_support/streams.py
Labels: change:unplanned

#2074 Revert "source-mysql: Set ReadTimeout/WriteTimeout on connection"
  source-mysql/main.go
Labels: change:unplanned

#2088 source-zendesk-support: add logging & `ticket_comments` checkpoint
  source-zendesk-support/source_zendesk_support/streams.py
Labels: change:unplanned

#2095 estuary-cdk: run `CaptureShim` as a coroutine
  estuary-cdk/estuary_cdk/shim_airbyte_cdk.py
Labels: change:unplanned

#2097 source-mysql: Improve connection error reporting
  source-mysql-batch/main.go
  source-mysql/main.go
Labels: change:unplanned
