Repository estuary/connectors, pull requests merged in 2025-06, with the labels that each got.

#2881 source-postgres: Set additionalProperties to false on array objects
  source-postgres/.snapshots/TestFeatureFlagFlattenArrays-Disabled-Discovery
  source-postgres/discovery.go
Labels: change:unplanned

#2887 source-postgres: Remove CTID ordering sanity check
  source-postgres/backfill.go
Labels: change:unplanned

#2947 source-postgres-batch: Fix TIME column discovery
  source-postgres-batch/.snapshots/TestDateAndTimeTypes-Capture
  source-postgres-batch/.snapshots/TestDateAndTimeTypes-Discovery
  source-postgres-batch/discovery.go
Labels: change:unplanned

#2960 Update NLTK to 3.9.1 to address security vulnerability
  estuary-cdk/poetry.lock
  estuary-cdk/pyproject.toml
  source-qualtrics/poetry.lock
  source-qualtrics/pyproject.toml
Labels: Security, change:unplanned

#2978 source-jira-legacy multiple dependency updates for vuln patching
  source-jira-legacy/poetry.lock
  source-jira-legacy/pyproject.toml
Labels: Security, dependencies, python, change:unplanned

#2979 source-braintree-native: Update security dependencies
  source-braintree-native/poetry.lock
  source-braintree-native/pyproject.toml
Labels: Security, dependencies, python

#2981 source-brevo: update dependencies due to vulnerabilities
  source-brevo/poetry.lock
  source-brevo/pyproject.toml
Labels: Security, dependencies, python

#2984 source-google-ads: update security dependencies to minimum versions
  source-google-ads/poetry.lock
  source-google-ads/pyproject.toml
Labels: Security, dependencies

#2985 source-linkedin-ads-v2: update security dependencies to minimum versions
  source-linkedin-ads-v2/poetry.lock
  source-linkedin-ads-v2/pyproject.toml
Labels: Security, dependencies

#2987 source-google-sheets-native: update security dependencies to address …
  source-google-sheets-native/poetry.lock
  source-google-sheets-native/pyproject.toml
  source-google-sheets-native/tests/snapshots/snapshots__discover__stdout.json
  source-google-sheets-native/tests/snapshots/snapshots__spec__stdout.json
Labels: dependencies

#2986 source-stripe-native: update security dependencies to minimum versions
  source-stripe-native/poetry.lock
  source-stripe-native/pyproject.toml
  source-stripe-native/tests/snapshots/snapshots__spec__stdout.json
Labels: dependencies

#2993 source-looker: update security dependencies to address vulnerabilities
  source-looker/poetry.lock
Labels: dependencies

#2991 source-sage-intacct: update security dependencies to address vulnerabilities
  source-sage-intacct/poetry.lock
Labels: dependencies

#2995 source-pendo: update security dependencies to address vulnerabilities
  source-pendo/poetry.lock
Labels: dependencies

#2992 source-pokemon: update security dependencies to address vulnerabilities
  source-pokemon/poetry.lock
Labels: dependencies

#2997 source-iterate: update security dependencies to address vulnerabilities
  source-iterate/poetry.lock
Labels: dependencies
