Repository estuary/connectors, pull requests merged in 2025-05, with the labels that each got.

#2763 source-firestore: Configurable backfill intervals
  source-firestore/.snapshots/TestSpec
  source-firestore/main.go
  source-firestore/main_test.go
  source-firestore/pull.go
Labels: change:unplanned

#2761 sqlcapture: Set additionalProperties: false in SourcedSchemas
  source-mysql/.snapshots/TestFeatureFlagEmitSourcedSchemas-Enabled
  source-postgres/.snapshots/TestFeatureFlagEmitSourcedSchemas-Enabled
  source-sqlserver/.snapshots/TestFeatureFlagEmitSourcedSchemas-Enabled
  sqlcapture/discovery.go
Labels: change:planned

#2770 snowflake: fix SHOW PIPES scan destination count
  materialize-snowflake/snowflake.go
Labels: change:emergency

#2762 source-postgres: Add "create_replication_slot" feature flag
  source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture2
  source-postgres/.snapshots/TestCaptureAfterSlotDropped-capture3
  source-postgres/capture_test.go
  source-postgres/database.go
  source-postgres/main.go
  source-postgres/prerequisites.go
  source-postgres/replication.go
Labels: change:unplanned

#2779 source-postgres: Avoid nil dereference in edge case
  source-postgres/datatypes.go
Labels: change:unplanned

#2796 source-sqlserver: Never emit nulls on NOT NULL column deletions
  source-sqlserver/.snapshots/TestBitNotNullDeletion
  source-sqlserver/datatypes_test.go
  source-sqlserver/replication.go
Labels: change:unplanned

#2828 source-mysql: Handle backfill query timeouts gracefully
  source-mysql/backfill.go
Labels: change:unplanned

#2833 source-boilerplate: Ensure stdout buffer flush on exit
  source-boilerplate/boilerplate.go
Labels: change:unplanned

#2834 source-postgres: Debug logging for empty deletion
  source-postgres/replication.go
Labels: change:unplanned

#2840 source-mysql-batch: Remove format:date for now
  source-mysql-batch/.snapshots/TestDateAndTimeTypes-Discovery
  source-mysql-batch/discovery.go
Labels: change:unplanned

#2843 source-postgres: Add value to debug logs
  source-postgres/replication.go
Labels: change:unplanned

#2844 source-postgres: Emit non-null values in keyOnly tuples
  source-postgres/replication.go
Labels: change:unplanned

#2870 source-mysql: Ignore INTVAR_EVENTs
  source-mysql/replication.go
Labels: change:unplanned

#2871 source-mysql: Improved UPDATE query handling
  source-mysql/replication.go
Labels: change:unplanned
